baseURL = "https://ivanluv555.github.io/blog/"
theme = "blowfish"
defaultContentLanguage = "zh-cn"
enableRobotsTXT = true
summaryLength = 30

[params]
  mainSections = ["posts"]

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
